#ifndef PCLITE_VERSION_H
#define PCLITE_VERSION_H

#define PCLITE_VERSION_MAJOR 0
#define PCLITE_VERSION_MINOR 1
#define PCLITE_VERSION_PATCH 1
#define PCLITE_VERSION_STRING "0.1.1"

#endif //PCLITE_VERSION_H
